#!/bin/bash

CDPATH=''

SAXON_URL=http://jedatwork.s3.amazonaws.com/blobs/saxon9he.jar

if [ ! -d __sb ]; then
  echo 'Not in project root. Aborting..'
  exit 1
fi

if [ ! -f __sb/saxon9he.jar ]; then
  curl "$SAXON_URL" >__sb/saxon9he.jar
fi

CONF="$(pwd)/sbrc.xml"
[ -f sbrc ] && CONF="$(pwd)/sbrc"

shopt -s extglob
LATEST='-1'
cd posts
for x in +([0-9]); do
  [ "$x" -gt "$LATEST" ] && LATEST="$x"
done
cd ..

(echo '<files xmlns="http://github.com/jedahu/static-blog">'
while read f; do
  if [ ${f:0:1} = '/' ]; then
    echo "$f"
  else
    echo "$(pwd)/$f"
  fi
done
echo '</files>') | \
  java -cp __sb/saxon9he.jar net.sf.saxon.Transform \
  -s:- \
  -xsl:_sb/sb.xsl \
  sbrc="$CONF" \
  latest-post="$LATEST" \
  files="$FILES"
