#!/bin/bash

set -e
CDPATH=''
ROOT=$(pwd)
if [ "$1" ]; then
  if [ ${1:0:1} = '/' ]; then
    ROOT="$1"
  else
    ROOT="$(pwd)/$1"
  fi
fi

SAXON_URL=http://jedatwork.s3.amazonaws.com/blobs/saxon9he.jar

if [ ! -f "$ROOT/__sb/saxon9he.jar" ]; then
  echo 'Downloading saxon..'
  curl "$SAXON_URL" >"$ROOT/__sb/saxon9he.jar"
fi

(echo '<files xmlns="http://github.com/jedahu/static-blog">'
while read f; do
  if [ ${f:0:1} = '/' ]; then
    echo "$f"
  else
    echo "$(pwd)/$f"
  fi
done
echo '</files>') | \
  java -cp "$ROOT/__sb/saxon9he.jar" net.sf.saxon.Transform \
  -s:- \
  -xsl:"$ROOT/_sb/sb.xsl" \
  root="$ROOT"
